### PR TITLE
add img (logo) and download api

### PR DESCRIPTION
**Pull request by pastleo**
img (logo) issues:

* https://github.com/zpao/qrcode.react/issues/70
* https://github.com/zpao/qrcode.react/issues/50
* https://github.com/zpao/qrcode.react/issues/46

download issues:

* https://github.com/zpao/qrcode.react/issues/37
* https://github.com/zpao/qrcode.react/issues/30

### CODE REVIEW

**Comment by pastleo** [comment]
a demo here: https://static.pastleo.me/qrcode.react-example/

**Comment by llmonkey** [comment]
@zpao Hi! Just want to confirm is this PR will be merged?
Thanks.

**Comment by TimorCookie** [comment]
> a demo here: https://static.pastleo.me/qrcode.react-example/

useful！

**Comment by pastleo** [comment]
for people who found here: if you want to install my fork to your project, you can do so by:

```shell
npm i https://github.com/pastleo/qrcode.react/releases/download/0.9.2.2/qrcode.react.tar.gz
# or
yarn add https://github.com/pastleo/qrcode.react/releases/download/0.9.2.2/qrcode.react.tar.gz
```

usage and demo: https://static.pastleo.me/qrcode.react-example/

**Comment by Alevale** [comment]
This PR is really useful, will it be merged? @zpao I think given the feedback it received it would be a massive addition

**Comment by Angelk90** [comment]
@pastleo :

It would be possible to generate the qr codes with the following graphic:

Link: [Site](https://www.qrcode-monkey.com/)

**Comment by ashconnell** [comment]
This library is great but is it now unmaintained?

**Comment by zpao** [comment]
I added support for embedding in #81 (and shipped in v1.0.0). I didn't add support for downloading yet as I don't think I want to do it the way you have here. In particular, I'm not convinced always rendering to canvas is best and I can see an argument for downloading the vector format if rendered as SVG. I'll leave this open to revisit. Thanks for doing this and inspiring me to actually get something supported!

**Comment by phlare** [comment]
would love if this was merged in (or these features implemented in another way)

**Comment by meabed** [comment]
This is super cool - @pastleo would you mind opening this pr here - i would love to help getting this feature: https://github.com/devmehq/react-qr-code

**Comment by pastleo** [comment]
> This is super cool - @pastleo would you mind opening this pr here - i would love to help getting this feature: https://github.com/devmehq/react-qr-code

I tried to clone and setup on my local machine, but I got this while `npm install`:

```
npm ERR! code ERESOLVE                                             
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!                                                           
npm ERR! While resolving: @devmehq/react-qr-code@1.0.3
npm ERR! Found: rollup@2.61.1                                      
npm ERR! node_modules/rollup                                       
npm ERR!   dev rollup@"2.61.1" from the root project
npm ERR!                                                           
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"6.0.4" from the root project
npm ERR!                                                           
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!                                                           
npm ERR! See /home/pastleo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pastleo/.npm/_logs/2021-12-21T08_01_29_181Z-debug.log
```

**Pull request closed without merging**
