### PR TITLE
The prop `includeMargin` can be set as number type

### PR DESCRIPTION
**Pull request by handycode**
see title

### CODE REVIEW

**Comment by listao** [comment]
Any updates or urgency to get this feature merged in?

**Comment by marcjulianfleck** [comment]
Is it possible to get that feature merged?

**Comment by emrockarts** [comment]
Would be great to get this featured merged if possible.

**Comment by Noitidart** [comment]
This is a great feature, exactly what I'm looking for. Thanks for providing it.

**Comment by meabed** [comment]
I use the library Thanks zpao! but it's seems unmaintained.

if any interested, I have updated the library and migrate it to typescript https://github.com/devmehq/react-qr-code
Also I have changed the includeMargin to MarginSize as number.

if you have any suggestion or improvement and you could open there, i'm happy to help adding more features and improvements to the library! thanks folks.

**Comment by Noitidart** [comment]
> I use the library Thanks zpao! but it's seems unmaintained.
> 
> if any interested, I have updated the library and migrate it to typescript https://github.com/devmehq/react-qr-code Also I have changed the includeMargin to MarginSize as number.
> 
> if you have any suggestion or improvement and you could open there, i'm happy to help adding more features and improvements to the library! thanks folks.

Oh wow fantastic, thank you!

**Comment by lovewinders** [comment]
me too

**Comment by Aumeeb** [comment]
Directly set the border : 6px solid #fff  on that Component without need property includeMargin
image

**Comment by handycode** [comment]
> noberk

I mean include customized margin in the image，not the css style.

**Comment by handycode** [comment]
Hi guys：
I  resolved the conflicts and changed it to the typescript version.

@zpao  Needing for review. ♥️

**Comment by zpao** [comment]
Apologies for the delays. I wasn't really supportive of this for a while but I've come around. Thanks for taking the time and rebasing recently.

I don't really want to overload `includeMargin` like this. I appreciate the backwards compatibility but I really hate type overloading.

Let's do this:
1. Introduce a new prop that is `marginSize` (I think… the name is somewhat confusing since `size` is also used for width where it is pixel count)
2. Deprecate `includeMargin`
3. In the transition state, when `marginSize` is specified, it overrides `includeMargin`.

If you're interested in doing this, that's great. But if I find some time I may take a stab at it.

Edit: I made #281 with what I said.

**Comment by zpao** [comment]
Closing in favor of #281 which I just merged. Thanks for the PR and feedback from others that they would find this valuable!

**Comment by handycode** [comment]
> I really hate type overloading

yeah,  I really hate type overloading too.

**Pull request closed without merging**
