### PR TITLE
Validate if string is null

### PR DESCRIPTION
**Pull request by lucodifier**

### CODE REVIEW

**Review by zpao — CHANGES_REQUESTED** [review]
We shouldn't be getting null/undefined in here. If we want the component to gracefully handled null/undefined (which, I don't know that I do) then it should be captured in `render` and we should return `null`. But as I noted on your issue, your code should probably check values to begine with.

**Comment by lucodifier** [comment]
The Value do not is Empty or Null.

Error:

[image: image.png]

**Comment by lucodifier** [comment]
And, with this palliative code:

[image: image.png]

QRCode is generated:

[image: image.png]

The value is:

https://homologacao.nfe.fazenda.sp.gov.br/cteConsulta/consulta/publica/ConsultarCTe.aspx?chaveAcesso=31210960860087003114641001000004131828017483

Thanks.

**Comment by lucodifier** [comment]
In addition, the error occurs in this lib qr.js/lib/QRCode and for some
unknown reason passes null value to function convertStr.
That's why validating the null value resolves per hour.

This is my html code:

[image: image.png]

Where the value of model.qrCodeUrl is a string containing a URL.

Regards.

**Comment by zpao** [comment]
I can't see what your code is, there are no images inline here (I think responding via email may not include those). That said, I'm fairly certain your code must be doing something that's resulting in null/undefined being passed in. Maybe via garbage collection of that model object and a re-render.

**Pull request closed without merging**
