### PR TITLE
Add ECC levels support

### PR DESCRIPTION
**Pull request by ziogaschr**
It will be nice to add support for handling error levels accuracy.

Keep up the good work.

Regards,
Chris

### CODE REVIEW

**Comment by zpao** [comment]
Awesome, looks good. I'm going to merge and then make a few changes. The first will probably be to default to H (since that's the current behavior - https://github.com/defunctzombie/qr.js/blob/master/index.js#L6-L7) and then also I guess just rewrite their whole thing since their handling of options doesn't allow M (same lines)

**Comment by zpao** [comment]
FYI: here's the followup commit: https://github.com/zpao/qrcode.react/commit/39f1b6b5bcfc969dceaa11159b4015978e722cf3

**Comment by ziogaschr** [comment]
Thanks @zpao. Your fix is awesome. :+1:

**Comment by ziogaschr** [comment]
Is pushing a new version with this feature in npm in your near roadmap?

**Comment by zpao** [comment]
Sorry about that, I meant to publish right away. Thanks for the reminder! I just shipped 0.6.0 with this.

**Pull request merged**
