### PR TITLE
add logo to qrcode

### PR DESCRIPTION
**Pull request by cssivision**
add logo to qrcode, just add image url.

### CODE REVIEW

**Comment by zpao** [comment]
Can you explain why you want this and show me a screenshot of this in action?

**Comment by cssivision** [comment]
just give a option to add logo in qrcode, a qrcode with logo is common, the logo maybe company logo or any other image people want. in my work, i use this component, but i have to add a logo to it, so i made this change.  qrcode with logo like this.
screen shot 2015-08-22 at 10 52 25

**Comment by wyvernnot** [comment]
+1

**Comment by scmx** [comment]
@zpao @cssivision
I rebased this branch on latest master and pushed the updated commit here with author preserved as @cssivision  https://github.com/scmx/qrcode.react/commit/ea1c2d31fbe556e3e4ecfa6e09e72196b700661b
(I also tweaked the if-statements to please `flow` regarding `ctx`)

@zpao Are you interested in having this feature?
@cssivision Your library https://github.com/cssivision/qrcode-react with image support works great, but it's currently throwing some react warnings https://github.com/cssivision/qrcode-react/issues/1, so I thought perhaps it would be possible to merge the two packages if this pull request was merged.

From what I can see the only thing that's missing now is the `logoWidth` and `logoHeight`. I can add a commit for that as well if you like?

**Comment by FayeFang** [comment]
@zpao Would love to include this feature in master! Embedding a vendor logo in a QRcode is a common practice in China. When customers see a known/verified logo, they are more willing to scan the QRCode.

Below is an example of with a Alipay (the largest online and mobile payment platform in China) logo.
585334a3bfbb9

**Comment by wesharehoodies** [comment]
+1 definitely good idea!

**Comment by zpao** [comment]
It's been a long time since I've commented. I've been working on adding this but in a way that maximizes image size without impacting the error correction of the qr code and without covering the essential components (dark module, finder patterns). Maybe that's overkill and just covering max N% is enough.

**Comment by brendonco** [comment]
Why this PR is not merge to master @zpao?

**Comment by philbarresi** [comment]
Is there any chance that this is going to be added in the future?

**Comment by zpao** [comment]
Going to finally close this out as I have an implementation that is what I want to ship in #81. Apologies for the super long delay in making this feature happen.

**Comment by Angelk90** [comment]
@zpao : When will you publish the new version to add the logo?

**Comment by zpao** [comment]
I shipped a new version last week.

**Pull request closed without merging**
